// <auto-generated />
using System;
using IkariDoTrainingBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IkariDoTrainingBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250219135343_FixFingerboardExerciseMapping")]
    partial class FixFingerboardExerciseMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IkariDoTrainingBackend.Models.Exercises.ExerciseBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("exercise_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int?>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_public");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<int?>("Repetitions")
                        .HasColumnType("int")
                        .HasColumnName("repetitions");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("exercise_base", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("IkariDoTrainingBackend.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<DateTime?>("SessionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("session_date");

                    b.HasKey("Id");

                    b.ToTable("sessions");
                });

            modelBuilder.Entity("IkariDoTrainingBackend.Models.SessionExercise", b =>
                {
                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int")
                        .HasColumnName("exercise_id");

                    b.Property<int?>("PauseTime")
                        .HasColumnType("int")
                        .HasColumnName("pause_time");

                    b.Property<int>("Sets")
                        .HasColumnType("int")
                        .HasColumnName("sets");

                    b.HasKey("SessionId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("session_exercises");
                });

            modelBuilder.Entity("IkariDoTrainingBackend.Models.TrainingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("goal");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.ToTable("training_plans");
                });

            modelBuilder.Entity("IkariDoTrainingBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("training_plan_sessions", b =>
                {
                    b.Property<int>("session_id")
                        .HasColumnType("int");

                    b.Property<int>("training_plan_id")
                        .HasColumnType("int");

                    b.HasKey("session_id", "training_plan_id");

                    b.HasIndex("training_plan_id");

                    b.ToTable("training_plan_sessions");
                });

            modelBuilder.Entity("IkariDoTrainingBackend.Models.Exercises.FingerboardExercise", b =>
                {
                    b.HasBaseType("IkariDoTrainingBackend.Models.Exercises.ExerciseBase");

                    b.Property<string>("BoardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("board_name");

                    b.Property<float>("EdgeSize")
                        .HasColumnType("float")
                        .HasColumnName("edge_size");

                    b.Property<string>("Fingers")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("fingers");

                    b.Property<string>("GripType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("grip_type");

                    b.ToTable("fingerboard_exercises", (string)null);
                });

            modelBuilder.Entity("IkariDoTrainingBackend.Models.Exercises.ExerciseBase", b =>
                {
                    b.HasOne("IkariDoTrainingBackend.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("IkariDoTrainingBackend.Models.SessionExercise", b =>
                {
                    b.HasOne("IkariDoTrainingBackend.Models.Exercises.ExerciseBase", "Exercise")
                        .WithMany("SessionExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkariDoTrainingBackend.Models.Session", "Session")
                        .WithMany("SessionExercises")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("training_plan_sessions", b =>
                {
                    b.HasOne("IkariDoTrainingBackend.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkariDoTrainingBackend.Models.TrainingPlan", null)
                        .WithMany()
                        .HasForeignKey("training_plan_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IkariDoTrainingBackend.Models.Exercises.FingerboardExercise", b =>
                {
                    b.HasOne("IkariDoTrainingBackend.Models.Exercises.ExerciseBase", null)
                        .WithOne()
                        .HasForeignKey("IkariDoTrainingBackend.Models.Exercises.FingerboardExercise", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IkariDoTrainingBackend.Models.Exercises.ExerciseBase", b =>
                {
                    b.Navigation("SessionExercises");
                });

            modelBuilder.Entity("IkariDoTrainingBackend.Models.Session", b =>
                {
                    b.Navigation("SessionExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
